### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by andyzeli** [andyzeli/Bil#2]
events on the calendar (react-big-calendar) should open a big modal instead of firing an alert. the modal should have the flexibility to pull any data from redux state. 

candidates: 
1. dan abramov's method https://stackoverflow.com/questions/35623656/how-can-i-display-a-modal-dialog-in-redux-that-performs-asynchronous-actions/35641680
or,
2. portals
3. ??

**Comment by andyzeli** [comment]
codemill$150

**Comment by denim2x** [comment]
@andyzeli some good modal [components](https://devarchy.com/react/need/overlay): [react-modal](https://reactcommunity.org/react-modal/), [react-modal-dialog](http://www.qimingweng.com/react-modal-dialog/), [react-redux-modal-flex](https://www.npmjs.com/package/react-redux-modal-flex), [react-skylight](http://marcio.github.io/react-skylight/), [rodal](http://chenjiahan.github.io/rodal/)

**Comment by andyzeli** [comment]
functionality added. closing
